services:
  mongodb:
    image: mongo:7.0
    container_name: fusionize-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: fusionize
      MONGO_INITDB_ROOT_PASSWORD: fusionize
      MONGO_INITDB_DATABASE: fuzdb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - fusionize-network

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: fusionize-rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: fusionize
      RABBITMQ_DEFAULT_PASS: fusionize
    ports:
      - "5672:5672"      # AMQP
      - "15672:15672"    # Management UI
      - "61613:61613"    # STOMP
    command: >
      bash -c "rabbitmq-plugins enable rabbitmq_stomp rabbitmq_web_stomp rabbitmq_management &&
               rabbitmq-server"
    networks:
      - fusionize-network

  keycloak-db:
    image: postgres:16
    container_name: fusionize-keycloak-db
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak_pg:/var/lib/postgresql/data
    networks:
      - fusionize-network

  keycloak:
    build:
      context: ./docker/keycloak
      dockerfile: Dockerfile
    container_name: fusionize-keycloak
    depends_on:
      - keycloak-db
    command:
      - start-dev
      - --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak

      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
    ports:
      - "8080:8080"
    networks:
      - fusionize-network

networks:
  fusionize-network:
    driver: bridge

volumes:
  mongo_data:
  keycloak_pg:
