server:
  port: 8081

spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7

  application:
    name: fusionize-orchestrator
  security:
    oauth2:
      client:
        registration:
          fusionize-client-credentials:
            client-id: fusionize-orchestrator
            client-secret: fusionize-secret
            authorization-grant-type: client_credentials
            scope: openid
            provider: fusionize
          fusionize-password:
            client-id: fusionize-orchestrator
            client-secret: fusionize-secret
            authorization-grant-type: password
            scope: openid
            provider: fusionize
        provider:
          fusionize:
            token-uri: http://localhost:8080/realms/fuz/protocol/openid-connect/token
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/fuz

fusionize:
  worker:
    orchestrator-url: http://localhost:8081
    orchestrator-mongo: mongodb://fusionize:fusionize@localhost:27017/fuzdb?authSource=admin
    orchestrator-amqp: amqp://fusionize:fusionize@localhost:5672
    oidc-client-id: fusionize-workers
    oidc-client-secret: fusionize-secret
    workflow-definitions-root: ./workflows
